import { Room } from "@/types";

export const mockRooms: Room[] = [
  {
    id: "1",
    roomNumber: "101",
    floor: 1,
    type: "Standard",
    maxOccupancy: 2,
    pricePerNight: 1200,
    status: "AVAILABLE",
    amenities: ["Wi-Fi", "TV", "Air Conditioning", "Hot Water"],
    images: ["https://placehold.co/400x300/e0e7ff/4338ca?text=Room+101"],
    description: "ห้องมาตรฐานพร้อมวิวสวน เหมาะสำหรับคู่รัก",
    createdAt: "2025-01-10",
  },
  {
    id: "2",
    roomNumber: "201",
    floor: 2,
    type: "Deluxe",
    maxOccupancy: 2,
    pricePerNight: 2500,
    status: "AVAILABLE",
    amenities: ["Wi-Fi", "TV", "Air Conditioning", "Hot Water", "Mini Bar", "Bathtub"],
    images: ["https://placehold.co/400x300/d1fae5/065f46?text=Room+201"],
    description: "ห้อง Deluxe วิวสระว่ายน้ำ ตกแต่งสไตล์โมเดิร์น",
    createdAt: "2025-01-10",
  },
  {
    id: "3",
    roomNumber: "301",
    floor: 3,
    type: "Suite",
    maxOccupancy: 4,
    pricePerNight: 5800,
    status: "AVAILABLE",
    amenities: ["Wi-Fi", "TV", "Air Conditioning", "Hot Water", "Mini Bar", "Bathtub", "Living Room", "Kitchen"],
    images: ["https://placehold.co/400x300/fef3c7/92400e?text=Room+301"],
    description: "Suite หรูพร้อมห้องนั่งเล่นและครัว วิวทะเล",
    createdAt: "2025-01-10",
  },
  {
    id: "4",
    roomNumber: "102",
    floor: 1,
    type: "Standard",
    maxOccupancy: 2,
    pricePerNight: 1200,
    status: "MAINTENANCE",
    amenities: ["Wi-Fi", "TV", "Air Conditioning", "Hot Water"],
    images: ["https://placehold.co/400x300/e0e7ff/4338ca?text=Room+102"],
    description: "ห้องมาตรฐานพร้อมวิวสวน",
    createdAt: "2025-01-10",
  },
  {
    id: "5",
    roomNumber: "202",
    floor: 2,
    type: "Family",
    maxOccupancy: 5,
    pricePerNight: 3500,
    status: "AVAILABLE",
    amenities: ["Wi-Fi", "TV", "Air Conditioning", "Hot Water", "Mini Bar", "Bunk Bed"],
    images: ["https://placehold.co/400x300/fce7f3/9d174d?text=Room+202"],
    description: "ห้องแฟมิลี่ขนาดใหญ่ เหมาะสำหรับครอบครัว",
    createdAt: "2025-01-10",
  },
  {
    id: "6",
    roomNumber: "302",
    floor: 3,
    type: "Suite",
    maxOccupancy: 4,
    pricePerNight: 5800,
    status: "INACTIVE",
    amenities: ["Wi-Fi", "TV", "Air Conditioning", "Hot Water", "Mini Bar", "Bathtub", "Living Room"],
    images: ["https://placehold.co/400x300/fef3c7/92400e?text=Room+302"],
    description: "Suite ขนาดใหญ่วิวสระว่ายน้ำ",
    createdAt: "2025-01-10",
  },
  {
    id: "7",
    roomNumber: "203",
    floor: 2,
    type: "Deluxe",
    maxOccupancy: 3,
    pricePerNight: 2800,
    status: "AVAILABLE",
    amenities: ["Wi-Fi", "TV", "Air Conditioning", "Hot Water", "Mini Bar"],
    images: ["https://placehold.co/400x300/d1fae5/065f46?text=Room+203"],
    description: "Deluxe พร้อมเตียง Extra Bed สำหรับ 3 คน",
    createdAt: "2025-01-12",
  },
  {
    id: "8",
    roomNumber: "103",
    floor: 1,
    type: "Standard",
    maxOccupancy: 2,
    pricePerNight: 1200,
    status: "AVAILABLE",
    amenities: ["Wi-Fi", "TV", "Air Conditioning"],
    images: ["https://placehold.co/400x300/e0e7ff/4338ca?text=Room+103"],
    description: "ห้องมาตรฐานราคาประหยัด",
    createdAt: "2025-01-15",
  },
];
