import { Room } from "@/types";

export const mockRoomsHome: Room[] = [
  {
    id: "1",
    roomNumber: "101",
    type: "Standard",
    floor: 1,
    maxOccupancy: 2,
    pricePerNight: 1200,
    description: "ห้องมาตรฐานวิวสวน ตกแต่งด้วยโทนสีอบอุ่น เหมาะสำหรับคู่รัก",
    images: ["/images/room-standard.jpg"],
    status: "AVAILABLE",
    amenities: ["Wi-Fi", "TV", "Air Conditioning", "Hot Water"],
  },
  {
    id: "2",
    roomNumber: "201",
    type: "Deluxe",
    floor: 2,
    maxOccupancy: 2,
    pricePerNight: 2500,
    description:
      "ห้อง Deluxe วิวสระว่ายน้ำ พร้อมอ่างอาบน้ำ ตกแต่งสไตล์โมเดิร์น",
    images: ["/images/room-deluxe.jpg"],
    status: "AVAILABLE",
    amenities: [
      "Wi-Fi",
      "TV",
      "Air Conditioning",
      "Hot Water",
      "Mini Bar",
      "Bathtub",
    ],
  },
  {
    id: "3",
    roomNumber: "301",
    type: "Suite",
    floor: 3,
    maxOccupancy: 4,
    pricePerNight: 5800,
    description: "Suite หรูพร้อมห้องนั่งเล่นและห้องครัว วิวทะเลแบบ Panoramic",
    images: ["/images/room-suite.jpg"],
    status: "AVAILABLE",
    amenities: [
      "Wi-Fi",
      "TV",
      "Air Conditioning",
      "Hot Water",
      "Mini Bar",
      "Bathtub",
      "Living Room",
      "Kitchen",
    ],
  },
  {
    id: "4",
    roomNumber: "202",
    type: "Family",
    floor: 2,
    maxOccupancy: 5,
    pricePerNight: 3500,
    description: "ห้องแฟมิลี่ขนาดใหญ่ เหมาะสำหรับครอบครัว มีเตียงสองชั้น",
    images: ["/images/room-family.jpg"],
    status: "AVAILABLE",
    amenities: [
      "Wi-Fi",
      "TV",
      "Air Conditioning",
      "Hot Water",
      "Mini Bar",
      "Bunk Bed",
    ],
  },
  {
    id: "5",
    roomNumber: "102",
    type: "Standard",
    floor: 1,
    maxOccupancy: 2,
    pricePerNight: 1200,
    description: "ห้องมาตรฐานพร้อมวิวสวนด้านหลัง บรรยากาศร่มรื่น",
    images: ["/images/room-standard-2.jpg"],
    status: "MAINTENANCE",
    amenities: ["Wi-Fi", "TV", "Air Conditioning"],
  },
  {
    id: "6",
    roomNumber: "203",
    type: "Deluxe",
    floor: 2,
    maxOccupancy: 3,
    pricePerNight: 2800,
    description: "Deluxe พร้อม Extra Bed สำหรับ 3 คน วิวสระว่ายน้ำ",
    images: ["/images/room-deluxe-2.jpg"],
    status: "AVAILABLE",
    amenities: ["Wi-Fi", "TV", "Air Conditioning", "Hot Water", "Mini Bar"],
  },
];
